-- SourceOS Terminal Workbench default WezTerm profile
--
-- Install by symlinking or copying this file to ~/.wezterm.lua, or require it
-- from an existing WezTerm config.
--
-- This profile is intentionally non-invasive. It provides SourceOS defaults
-- without changing WezTerm internals.

local wezterm = require 'wezterm'
local mux = wezterm.mux
local act = wezterm.action

local config = wezterm.config_builder()

local function env(name, fallback)
  local value = os.getenv(name)
  if value == nil or value == '' then
    return fallback
  end
  return value
end

local function basename(path)
  if path == nil then
    return ''
  end
  return string.gsub(path, '(.*[/\\])', '')
end

local function sourceos_workspace()
  return env('SOURCEOS_WORKSPACE', 'sourceos')
end

local function sourceos_domain()
  return env('SOURCEOS_EXECUTION_DOMAIN', 'host')
end

local function sourceos_session_id()
  return env('SOURCEOS_TERMINAL_SESSION_ID', '')
end

config.default_prog = nil
config.automatically_reload_config = true
config.check_for_updates = false

-- Keep upstream theme compatibility while providing a calm SourceOS default.
config.color_scheme = env('SOURCEOS_WEZTERM_COLOR_SCHEME', 'Builtin Solarized Dark')
config.font = wezterm.font_with_fallback({
  'JetBrains Mono',
  'Symbols Nerd Font Mono',
  'Noto Color Emoji',
})
config.font_size = tonumber(env('SOURCEOS_WEZTERM_FONT_SIZE', '12.5'))

config.window_padding = {
  left = 8,
  right = 8,
  top = 6,
  bottom = 6,
}

config.use_fancy_tab_bar = false
config.hide_tab_bar_if_only_one_tab = false
config.tab_bar_at_bottom = false
config.window_decorations = 'RESIZE'
config.audible_bell = 'Disabled'
config.enable_scroll_bar = false
config.scrollback_lines = 20000

-- SSH and mux workflows are core to SourceOS terminal fabric. The actual
-- domain definitions should be generated by SourceOS workspace tooling later.
config.unix_domains = {
  {
    name = 'sourceos-local',
  },
}

config.set_environment_variables = {
  SOURCEOS_TERMINAL_FRONTEND = 'wezterm',
  SOURCEOS_TERMINAL_PROFILE = 'sourceos-v0',
}

config.keys = {
  -- Pane control
  { key = 'Enter', mods = 'CTRL|SHIFT', action = act.SplitVertical { domain = 'CurrentPaneDomain' } },
  { key = 'Enter', mods = 'CTRL|ALT', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
  { key = 'w', mods = 'CTRL|SHIFT', action = act.CloseCurrentPane { confirm = true } },

  -- Tab control
  { key = 't', mods = 'CTRL|SHIFT', action = act.SpawnTab 'CurrentPaneDomain' },
  { key = 'LeftArrow', mods = 'CTRL|SHIFT', action = act.ActivateTabRelative(-1) },
  { key = 'RightArrow', mods = 'CTRL|SHIFT', action = act.ActivateTabRelative(1) },

  -- Navigation
  { key = 'h', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Left' },
  { key = 'j', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Down' },
  { key = 'k', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Up' },
  { key = 'l', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Right' },

  -- Search and copy mode
  { key = 'f', mods = 'CTRL|SHIFT', action = act.Search 'CurrentSelectionOrEmptyString' },
  { key = 'x', mods = 'CTRL|SHIFT', action = act.ActivateCopyMode },

  -- Launcher and command palette
  { key = 'p', mods = 'CTRL|SHIFT', action = act.ActivateCommandPalette },
  { key = 'o', mods = 'CTRL|SHIFT', action = act.ShowLauncher },

  -- SourceOS reserved leader-style actions. These should later call a sidecar
  -- through wezterm cli / shell wrapper integration, not bypass policy.
  {
    key = 's',
    mods = 'CTRL|SHIFT',
    action = act.PromptInputLine {
      description = 'SourceOS session note',
      action = wezterm.action_callback(function(window, pane, line)
        if line and line ~= '' then
          wezterm.log_info('sourceos.session_note: ' .. line)
        end
      end),
    },
  },
}

wezterm.on('format-tab-title', function(tab, tabs, panes, config_, hover, max_width)
  local pane = tab.active_pane
  local cwd = ''

  if pane and pane.current_working_dir then
    cwd = basename(tostring(pane.current_working_dir))
  end

  if cwd == '' then
    cwd = 'terminal'
  end

  local domain = sourceos_domain()
  local workspace = sourceos_workspace()
  local title = string.format(' %s:%s [%s] ', workspace, cwd, domain)

  return title
end)

wezterm.on('update-right-status', function(window, pane)
  local workspace = sourceos_workspace()
  local domain = sourceos_domain()
  local session = sourceos_session_id()

  if session ~= '' then
    session = ' · ' .. session
  end

  window:set_right_status(string.format(' %s · %s%s ', workspace, domain, session))
end)

wezterm.on('gui-startup', function(cmd)
  local workspace = sourceos_workspace()
  pcall(function()
    mux.set_active_workspace(workspace)
  end)
end)

return config
